addons:
  sonarcloud:
    organization: hsweb
    token:
      secure: fba01e9fb57104fd0cfbed380e8c90301e35ff09
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2/repository
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn test sonar:sonar
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
